[package]
name = "hist"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
bytemuck = { version = "1.22.0", features = ["derive"] }
cgmath = { version = "0.18.0", features = ["swizzle"] }
vulkano = "0.35.1"
winit = "0.30.9"
